# CI for Fast CDR repository
# The Action is triggered with a PR or push and every night at 00:00
# Additionally, it can be also triggered manually

name: fastcdr-test

on:

  schedule:
    - cron: '0 0 * * *'

  push:

  workflow_dispatch:
    inputs:
      cmake_args:
        description: 'Optional CMake arguments'
        required: false
        type: string
        default: ''
      ctest_args:
        description: 'Optional CTest arguments'
        required: false
        type: string
        default: ''

  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  echo-step:
    runs-on: ubuntu-latest
    steps:
      - id: dummy-echo
        run: |
          echo "HELLO_WORLD"